/**
 * Curated country list for the Contact and Newsletter forms.
 * Ordered: most-relevant first (Kiut's key territories), then alphabetical.
 */

export const COUNTRIES: string[] = [
  // ── Key territories first ───────────────────────────────────────────────────
  "Nigeria",
  "United States",
  "United Kingdom",
  "Canada",
  "Ghana",
  "South Africa",
  "Kenya",
  "Jamaica",
  "Trinidad and Tobago",
  "France",
  "Germany",
  "Netherlands",
  // ── Rest of Africa ──────────────────────────────────────────────────────────
  "Algeria",
  "Angola",
  "Botswana",
  "Cameroon",
  "Côte d'Ivoire",
  "DR Congo",
  "Egypt",
  "Ethiopia",
  "Gabon",
  "Malawi",
  "Mali",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Rwanda",
  "Senegal",
  "Sierra Leone",
  "Tanzania",
  "Togo",
  "Tunisia",
  "Uganda",
  "Zambia",
  "Zimbabwe",
  // ── Americas ────────────────────────────────────────────────────────────────
  "Argentina",
  "Barbados",
  "Brazil",
  "Colombia",
  "Cuba",
  "Dominican Republic",
  "Guyana",
  "Haiti",
  "Mexico",
  "Panama",
  "Peru",
  "Puerto Rico",
  "Suriname",
  // ── Europe ──────────────────────────────────────────────────────────────────
  "Austria",
  "Belgium",
  "Cyprus",
  "Denmark",
  "Finland",
  "Greece",
  "Ireland",
  "Italy",
  "Norway",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "Spain",
  "Sweden",
  "Switzerland",
  "Ukraine",
  // ── Middle East ─────────────────────────────────────────────────────────────
  "Israel",
  "Lebanon",
  "Qatar",
  "Saudi Arabia",
  "Turkey",
  "UAE",
  // ── Asia-Pacific ────────────────────────────────────────────────────────────
  "Australia",
  "China",
  "India",
  "Indonesia",
  "Japan",
  "Malaysia",
  "New Zealand",
  "Philippines",
  "Singapore",
  "South Korea",
  "Thailand",
  // ── Catch-all ───────────────────────────────────────────────────────────────
  "Other",
];
