/**
 * Hero image registry — blur-up (LQIP) placeholders for HeroSection.
 *
 * Generated by scripts/generate-hero-images.mjs, which writes a
 * <slug>.meta.json alongside each variant set at
 * client/public/images/hero/<slug>/. Paste the blurDataURL here whenever a
 * new hero image is generated so <HeroSection slug="..."> can paint an
 * instant placeholder while the real image loads.
 */
export interface HeroImageMeta {
  blurDataURL: string;
}

export const heroImageMeta: Record<string, HeroImageMeta> = {
  tour: {
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAMEBf/EAB0QAAICAwADAAAAAAAAAAAAAAACAxEBBDEUIVH/xAAWAQEBAQAAAAAAAAAAAAAAAAAEAQL/xAAZEQEBAAMBAAAAAAAAAAAAAAABAAIDEiH/2gAMAwEAAhEDEQA/AOMy5dfYi1ryS8jPw0a09twT2BH5VqPqUvAVmnpOAmOzy067/9k=",
  },
  about: {
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAMFAQT/xAAbEAADAAIDAAAAAAAAAAAAAAAAAQIDBBMhQf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAWEQEBAQAAAAAAAAAAAAAAAAABAAL/2gAMAwEAAhEDEQA/AJ0RLGcS8J8ZqO3Xt0uwO2ZgsyQkgF7FuWAjbFwX/9k=",
  },
  videos: {
    blurDataURL:
      "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIEBf/EAB4QAAIBBAMBAAAAAAAAAAAAAAABAwIEEiERE0Ex/8QAFQEBAQAAAAAAAAAAAAAAAAAAAwT/xAAYEQADAQEAAAAAAAAAAAAAAAAAAQIREv/aAAwDAQACEQMRAD8Axu1OopiaeyS2hz+s0Y7bj0KkVTWIZVJ6AWSPD0A+RFR//9k=",
  },
};
